# Copyright 2024-2025 by the BurstCube Team.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License
# is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied. See the License for the specific language governing permissions and limitations under the
# License.
#
"""The BurstCube mission timeline: a reconstructed log of spacecraft/instrument
events from ``trend/timeline/*_timeline_final.csv``, a 3-column file with no
header row: ``MET, UTC-string, event-description``.

**The CSV's own UTC column is wrong by exactly +37 s** (verified): it was
evidently generated by treating MET as a count of TAI seconds since
2021-01-01 00:00:00 UTC, omitting the TAI-UTC leap-second offset -- the same
37 s leap-second omission described in archive caveat #11. The FITS files
are authoritative, so this reader:

* parses the MET column and converts it with :class:`~gdt.missions.burstcube.time.BurstCubeSecTime`
  (exposed as :attr:`~BurstCubeTimeline.time`);
* does **not** trust the CSV's UTC column, exposing it separately, unconverted,
  as :attr:`~BurstCubeTimeline.utc_as_written`, with this discrepancy
  documented rather than corrected.

Per archive caveat #6, the timeline is reconstructed from mixed packet types
at different cadences, so events can appear out of order by seconds; this
reader does not re-sort them.
"""
import csv
import re
from pathlib import Path
from typing import Union

import numpy as np

from .time import Time

__all__ = ['BurstCubeTimeline']

# "CBD Data Timestamp Drift (GPS Reboot). Unnaccounted absolute time drift: X"
# -- note the source's own misspelling "Unnaccounted", reproduced verbatim.
_DRIFT_PATTERN = re.compile(r'Unnaccounted absolute time drift:\s*([+-]?\d+(?:\.\d+)?)')


class BurstCubeTimeline:
    """The BurstCube mission timeline.

    Args:
        met (numpy.ndarray): The MET (column 0) of each event
        utc_as_written (numpy.ndarray of str): The CSV's own UTC string
            (column 1) of each event -- see the module docstring for why
            this is untrustworthy
        description (numpy.ndarray of str): The event description (column 2),
            verbatim
    """

    def __init__(self, met, utc_as_written, description):
        self._met = np.asarray(met, dtype=float)
        self._utc_as_written = np.asarray(utc_as_written, dtype=object)
        self._description = np.asarray(description, dtype=object)
        self._drift_seconds = self._parse_drift(self._description)

    @property
    def num_rows(self):
        """(int): The number of timeline events."""
        return self._met.size

    @property
    def time(self):
        """(astropy.time.Time): The authoritative event times, from the MET
        column, converted with :class:`~gdt.missions.burstcube.time.BurstCubeSecTime`.
        """
        return Time(self._met, format='burstcube')

    @property
    def utc_as_written(self):
        """(numpy.ndarray of str): The CSV's own UTC string for each event.
        **Do not use this for analysis**: it is 37.000 s earlier than
        :attr:`time` (converted to UTC) for every row in the file this was
        verified against, apparently from treating MET as TAI seconds since
        the epoch. Kept only for reference/debugging against the raw file.
        """
        return self._utc_as_written

    @property
    def description(self):
        """(numpy.ndarray of str): The raw event description for each event,
        exactly as written in the CSV -- including the source's own
        misspellings ("Continous", "Unnaccounted"). Not normalized or
        corrected; use :meth:`matching` to search it.
        """
        return self._description

    @property
    def drift_seconds(self):
        """(numpy.ndarray of float): The drift magnitude, in seconds, parsed
        out of the "CBD Data Timestamp Drift (GPS Reboot)" rows' own
        description text. ``NaN`` for every other row.
        """
        return self._drift_seconds

    def matching(self, substring):
        """Select the events whose description contains a substring.

        Note:
            Matching is a plain, case-sensitive substring search against the
            raw description text. The source's own two misspellings are not
            normalized, so match "Continous" and "Unnaccounted" (not
            "Continuous"/"Unaccounted") if searching for those events.

        Args:
            substring (str): The substring to match, e.g.
                ``'Spacecraft Reboot'`` or ``'Unnaccounted'``.

        Returns:
            (numpy.ndarray of bool): A mask into this timeline's rows.
        """
        return np.array([substring in d for d in self._description])

    @classmethod
    def open(cls, file_path: Union[str, Path]):
        """Read a BurstCube timeline CSV file.

        Args:
            file_path (str): The path to the ``*_timeline_final.csv`` file

        Returns:
            (:class:`BurstCubeTimeline`)
        """
        met, utc, description = [], [], []
        with open(file_path, newline='') as fh:
            for row in csv.reader(fh):
                if not row:
                    continue
                met.append(float(row[0]))
                utc.append(row[1])
                description.append(row[2])
        return cls(met, utc, description)

    @staticmethod
    def _parse_drift(description):
        drift = np.full(len(description), np.nan)
        for i, text in enumerate(description):
            match = _DRIFT_PATTERN.search(text)
            if match:
                drift[i] = float(match.group(1))
        return drift
